services:
  app:
    image: ghcr.io/the-monkeys/the_monkeys:latest
    container_name: the-monkeys

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env.local

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s


    networks:
      - monkeys_engine_monkeys

networks:
  monkeys_engine_monkeys:
    external: true
